from pathlib import Path
import json,html
p=Path(__file__).parent
products=json.loads((p/'data/product_reference_manifest.json').read_text())
esc=html.escape
header='''<a class="skip" href="#main">Skip to content</a><div class="concept">Independent Phasefield concept · Not commissioned by or affiliated with Detroit Flower Company · No orders or payments · <a href="pitch.html">Presenter story</a></div><header><div class="wrap nav"><a class="brand" href="index.html">DETROIT<br>FLOWER COMPANY<small>INDEPENDENT CONCEPT</small></a><nav aria-label="Main"><a href="index.html#shop">Shop flowers</a><a href="index.html#signature">Signature & custom</a><a href="index.html#secret">Secret Admirer</a><a href="delivery.html">Delivery & FAQ</a><a href="cart.html">Demo bag <span data-cart-count>(0)</span></a></nav></div></header><div class="availability" data-operational>Public policy reference: online same-day eligibility before 11 a.m.; Sunday closed. Actual product/date availability requires confirmation. All catalog availability below is simulated.</div>'''
footer='''<footer class="footer"><div class="wrap"><strong>FLOWERS WITH PERSONALITY.<br>EXPERIENCES WITH PURPOSE.</strong><small>Independent concept by Phasefield — Marketing & Revenue Systems. Not approved, commissioned or endorsed by Detroit Flower Company. Reference prices captured October 9, 2026; illustration and availability are simulated. No customer data, orders or payments are collected.</small></div></footer><div class="sr-only" role="status" aria-live="polite" id="announce"></div>'''
def page(title,body):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Independent Phasefield adaptive storefront concept. Illustrative catalog, no checkout."><title>{esc(title)} | Phasefield concept</title><link rel="stylesheet" href="assets/storefront.css"></head><body>{header}<main id="main" tabindex="-1">{body}</main>{footer}<script id="catalog-data" type="application/json">{json.dumps(products).replace('<','\\u003c')}</script><script src="assets/baseline.js" defer></script><script type="module" src="assets/app.mjs"></script></body></html>'''
def card(x):
 return f'''<article class="card" data-product="{x['id']}" data-price="{x['reference_price']}" data-category="{x['category']}"><a href="product-{x['id']}.html"><img src="{x['image']}" width="600" height="600" loading="lazy" alt="Original {x['styles'][0]} floral concept illustration, not this merchant product"><div class="meta"><h3>{esc(x['title'])}</h3><span class="price">${x['reference_price']}</span></div></a><span class="tag {'warn' if x['lead_time_days'] or not x['demo_available'] else ''}" data-eligibility>{'3-day advance reference' if x['lead_time_days'] else 'Unavailable demo fixture' if not x['demo_available'] else 'Availability simulated'}</span><p>Reference price · Concept illustration</p></article>'''
options=lambda a:''.join(f'<option value="{v}">{t}</option>' for v,t in a)
budgets=options([('all','Any budget'),('under75','Under $75'),('75to125','$75–under $125'),('125to200','$125–under $200'),('statement','$200 and above')])
styles=options([('all','Any style'),('playful','Bright & playful'),('classic','Classic roses'),('bold','Bold statement'),('custom','Something custom')])
mission='''<div class="missions"><div class="wrap mission-row adapt-controls"><span>What’s the moment?</span><button class="light" data-mission="default" aria-pressed="true">Just browsing</button><button class="light" data-mission="urgent" aria-pressed="false">Need it soon</button><button class="light" data-mission="mothers_day_discovery" aria-pressed="false">Mother’s Day demo</button><button class="light" data-mission="secret_admirer" aria-pressed="false">Secret Admirer</button></div><div class="wrap nojs-only mission-row"><span>Find your moment</span><a href="#shop">All flowers</a><a href="#signature">Something custom</a><a href="#secret">Secret Admirer</a></div></div>'''
filters=f'''<div class="filters adapt-controls"><label>Budget<select id="budget">{budgets}</select></label><label>Style<select id="style">{styles}</select></label><label>Fulfillment<select id="mode"><option value="delivery">Delivery simulation</option><option value="pickup">Pickup simulation</option></select></label><label>Timing<select id="timing"><option value="today">Today simulation</option><option value="next">Later date simulation</option></select></label><label>Collection<select id="category"><option value="all">All gifts</option><option value="roses">Roses</option><option value="mixed">Mixed blooms</option><option value="statement">Statement</option><option value="novelty">Novelty</option><option value="custom">Custom</option></select></label></div>'''
sap='''<section class="sap" id="secret"><div class="wrap"><span class="eyebrow">Something different, handled thoughtfully</span><h2>A surprise, with consent first.</h2><p>In the public Secret Admirer program, recipient consent is required before fulfillment. This concept shows the journey without collecting anyone’s details.</p><div class="notice">Need a specific date, or know the person personally? Choose standard gifting. Same-day consent is not guaranteed.</div><div class="steps"><article><b>01 / CHOOSE</b><h3>Find the surprise</h3><p>Browse eligible demo arrangements.</p></article><article><b>02 / REACH</b><h3>A sample contact</h3><p>Presenter example only: <strong>@example_recipient</strong>. No editable handle field.</p></article><article><b>03 / CONSENT</b><h3>Permission, then flowers</h3><p>In the merchant’s program, consent comes before fulfillment. Timing depends on that response.</p></article></div><div class="actions adapt-controls"><button data-mission="secret_admirer">Explore the special journey</button><button class="light" data-mission="default">Choose standard gifting</button></div></div></section>'''
faq='''<section class="content" id="faq"><div class="wrap faq"><div><span class="eyebrow">Before the big moment</span><h2>Good flowers.<br>Clear expectations.</h2><p>Public policy references, simplified for this demonstration. Store confirmation is required before real orders.</p><a class="button light" href="delivery.html">Delivery & FAQ</a></div><div><details><summary>Can flowers arrive today?</summary><p>The public website states online orders before 11 a.m. are eligible for same-day delivery. Product lead time, capacity and destination still need confirmation. Sunday is closed.</p></details><details><summary>What happens after the cutoff?</summary><p>Online orders after 11 a.m. are processed the next business day according to the public homepage. Ask the store about other options; this concept cannot confirm them.</p></details><details><summary>Can I choose an exact delivery time?</summary><p>The merchant’s public policy does not guarantee exact times. No date or delivery-time promise is made by this demo.</p></details><details><summary>Can I customize an arrangement?</summary><p>The public catalog includes color, wrapping, cards and other custom options. Approved choices and prices vary by product and need client validation.</p></details><details><summary>Is this a real store?</summary><p>No. This is an independent concept by Phasefield. All cart actions are simulated. Product images are original illustrations, not merchant photography.</p></details></div></div></section>'''
presenter='''<details class="presenter adapt-controls" id="presenter"><summary>Presenter controls · simulation and rule trace</summary><div><label>Detroit simulation time<select id="clock"><option value="2026-10-09T10:30:00-04:00">Friday 10:30 a.m. · before cutoff</option><option value="2026-10-09T10:59:00-04:00">Friday 10:59 a.m.</option><option value="2026-10-09T11:00:00-04:00">Friday 11:00 a.m. · at cutoff</option><option value="2026-10-09T11:01:00-04:00">Friday 11:01 a.m.</option><option value="2026-10-11T10:30:00-04:00">Sunday · closed</option><option value="invalid">Missing/invalid time</option></select></label><label>Fixture availability<select id="stock"><option value="normal">Normal demo fixtures</option><option value="none">All unavailable</option></select></label><button class="light" id="reset">Reset to default</button><button class="light" id="fail">Simulate adaptive failure</button><p class="status" id="rule-trace">Default server-rendered storefront.</p><pre id="events" aria-label="Local demo event log"></pre></div></details>'''
body='''<section class="hero"><div class="hero-copy"><span class="eyebrow" data-hero-eyebrow>Made for your kind of moment</span><h1 data-hero-title>Detroit flowers with personality.</h1><p data-hero-body>Big feelings. Bold bouquets. Custom details that make it yours.</p><a class="button" data-hero-cta href="#shop">Browse bouquets</a></div><figure><img src="assets/hero.webp" width="1536" height="1024" fetchpriority="high" alt="Original concept bouquet with bold pink and red flowers in expressive wrapping"><figcaption class="image-caption">Original floral concept · not merchant photography</figcaption></figure></section>'''+mission+'''<section class="content" id="shop"><div class="wrap"><div class="section-head"><div><span class="eyebrow">A little gesture. A lot of personality.</span><h2>Pick your kind of wow.</h2></div><p>Explore a representative reference catalog. Prices are public references; availability and visuals are illustrative.</p></div>'''+filters+'''<div class="guidance" id="guidance">Start with the feeling. Make it personal with a card, color or custom detail.</div><p class="status" id="result-count">14 reference arrangements · browse all below.</p><div class="grid" id="product-grid">'''+''.join(card(x) for x in products if x['category']!='add-ons')+'''</div><div class="empty" id="empty" hidden>No demo arrangements match this selection. Broaden the budget, choose another timing or return to all gifts. <button class="light" data-mission="default">Return to all gifts</button></div></div></section><section class="feature" id="signature"><div class="wrap split"><div><span class="eyebrow">Make it unmistakably yours</span><h2>The detail makes<br>the difference.</h2><p>A favorite color. A bold wrap. A personal finishing touch. The public catalog’s customization is part of the brand’s strength; this concept brings the choices into clearer view.</p><a class="button light" href="product-pf-14.html">Explore a custom reference</a></div><img src="assets/playful.webp" width="1024" height="1024" loading="lazy" alt="Original pastel floral illustration, not a catalog photograph"></div></section>'''+sap+faq+presenter
(p/'index.html').write_text(page('Detroit flowers with personality',body))
for x in products:
 b=f'''<div class="wrap"><div class="pdp"><div><img src="{x['image']}" width="800" height="800" alt="Original floral concept illustration, not a photograph of {esc(x['title'])}"><p>Concept illustration only. Actual arrangement appearance requires merchant photography.</p></div><div><a href="index.html#shop">Back to all gifts</a><h1>{esc(x['title'])}</h1><p class="price">${x['reference_price']} <small>reference price</small></p><div class="notice">{'Public reference: order 3 days in advance. Calendar/business-day interpretation needs client validation.' if x['lead_time_days'] else 'Availability is a demonstration fixture, not merchant inventory.'}</div><p data-pdp-availability data-id="{x['id']}">Actual timing and availability must be confirmed with the store.</p><h2 style="font-size:28px">Make it yours</h2><p>Preset choices demonstrate the customization flow. They are not verified merchant options or paid add-ons.</p><label for="custom">Concept styling choice</label><select id="custom"><option value="Florist-choice concept">Florist-choice concept</option><option value="Color preference concept">Color preference concept</option><option value="Personal detail concept">Personal detail concept</option></select><button disabled id="add-cart" data-id="{x['id']}">Add to demo bag</button><p id="cart-feedback" role="status"></p><noscript><p>Interactive demo bag needs JavaScript. You can still browse the full catalog and delivery information. No real checkout exists.</p></noscript><div class="notice">No recipient, card message, payment or photo upload is collected. Secret Admirer requires consent and cannot guarantee a specific date.</div><p><a href="cart.html">View demo bag</a> · <a href="delivery.html">Delivery & FAQ</a> · <a href="{x['source_url']}" rel="noreferrer" target="_blank">Public product reference (opens new tab)</a></p></div></div></div>'''
 (p/f"product-{x['id']}.html").write_text(page(x['title'],b))
(p/'delivery.html').write_text(page('Delivery & FAQ','<section class="content"><div class="wrap"><span class="eyebrow">Policy references, not a promise</span><h1 class="page-title">Know the timing.<br>Enjoy the moment.</h1><div class="notice">No delivery zones, exact times, holiday exceptions or refund terms have been approved for this concept. A real implementation requires merchant validation.</div></div></section>'+faq+sap))
(p/'cart.html').write_text(page('Your demo bag','''<section class="content"><div class="wrap"><span class="eyebrow">Simulation only</span><h1 class="page-title">Your demo bag.</h1><div class="notice">This bag cannot place an order. No checkout, payment, recipient or address collection is connected. Prices are reference base prices; tax, delivery fees and custom surcharges are not calculated.</div><div id="cart-lines"></div><div class="cart-total" id="cart-total"></div><noscript><p>This simulated cart requires JavaScript. <a href="index.html#shop">Browse reference arrangements</a> and <a href="delivery.html">read delivery guidance</a> without it.</p></noscript><a class="button light" href="index.html#shop">Keep exploring</a></div></section>'''))
print('Built 18 baseline pages')
