import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {parseCampaign,cleanContext,selectMission,operational,rankProducts,earliestFixture,makeEvent} from '../assets/engine.mjs';
const products=JSON.parse(fs.readFileSync(new URL('../data/product_reference_manifest.json',import.meta.url)));
test('15 attributed, classified records',()=>{assert.equal(products.length,15);assert.equal(new Set(products.map(p=>p.id)).size,15);for(const p of products)for(const k of ['source_url','price_reference_date','asset_rights_status','availability_evidence','lead_time_evidence','client_validation'])assert.ok(p[k]);});
test('campaign allowlist, defaults and conflicts',()=>{for(const [input,state] of [['%%%','default'],['?pf_mission=urgent','urgent'],['?pf_mission=discovery','mothers_day_discovery'],['?pf_mission=secret_admirer','secret_admirer'],['?pf_mission=<img onerror=alert(1)>','default'],['?pf_mission=urgent&pf_mission=discovery','default'],['?utm_campaign=secret_admirer','default']])assert.equal(parseCampaign(input).state,state);});
test('visitor priority, seasonal continuity',()=>{const c=selectMission(parseCampaign('?pf_mission=discovery'),'urgent');assert.equal(c.source,'visitor');assert.equal(c.occasion,'mothers_day');assert.equal(c.state,'urgent');});
test('cutoff boundaries, timezone, Sunday and invalid time',()=>{for(const [time,ok] of [['2026-10-09T10:59:00-04:00',true],['2026-10-09T11:00:00-04:00',false],['2026-10-09T11:01:00-04:00',false],['2026-10-11T10:30:00-04:00',false],['2026-10-09T14:59:00Z',true]])assert.equal(operational(time).eligible,ok);assert.equal(operational('bad').reason,'unknown');});
test('availability before budget and style, prices invariant',()=>{const before=JSON.stringify(products),c=cleanContext({state:'urgent',budget:'under75'});assert.ok(rankProducts(products,c).every(p=>p.reference_price<75&&p.lead_time_days===0));assert.equal(rankProducts(products,c,'2026-10-09T11:00:00-04:00').length,0);assert.ok(rankProducts(products,{state:'urgent',timing:'next'}).some(p=>p.lead_time_days===3));assert.equal(rankProducts(products,{style:'classic'})[0].styles[0],'classic');assert.equal(JSON.stringify(products),before);});
test('malformed and unavailable fixtures fail safely',()=>{assert.deepEqual(rankProducts([null,{},...products.map(p=>({...p,reference_price:NaN}))],{}),[]);assert.equal(rankProducts(products,{},undefined,products.map(p=>p.id)).length,0);assert.ok(!rankProducts(products,{}).some(p=>p.id==='pf-07'));});
test('date fixture skips closed Sunday and respects 3 days',()=>{assert.match(earliestFixture('2026-10-10T11:00:00-04:00'),/2026-10-12/);assert.match(earliestFixture('2026-10-09T10:00:00-04:00',3),/2026-10-12/);assert.match(earliestFixture('bad'),/Confirm/);});
test('event payload excludes personal data',()=>{const e=makeEvent('pf_product_clicked',{state:'urgent'},{product:'pf-01',handle:'person',url:'private',message:'private'});assert.equal(e.product,'pf-01');for(const k of ['handle','url','message'])assert.equal(k in e,false);});

test('missing catalog and null preference context fail safely',()=>{assert.equal(cleanContext(null).state,'default');assert.deepEqual(rankProducts(null,null,'invalid',null),[]);assert.equal(parseCampaign('?pf_mission=constructor').source,'default');assert.equal(parseCampaign('?pf_mission=__proto__').source,'default');});
